### ISSUE TITLE
Values vs references for math constructs.

### ISSUE THREAD

**Issue by agrande** [toxicFork/react-three-renderer#21]
I really like the way you dealt with materials as component, working with values instead of references.

I wish there could be an easy way to have THREE.Vector3 and other math classes dealt with as values, without having to either create a new one at each render (doesn't look good performance-wise) or save a reference as class member (as done in the example).

I suppose you already thought of this question. Any plan to deal with this?

**Comment by toxicFork** [comment]
From my understanding, you are proposing something similar to:
```jsx
<vector3 x={} y={} z={}/>
```
However, I believe that this would be too costly, as there would be too many of these elements around, and for each of them react will need to check multiple props every time you want to change any of them. 

And usually positions / rotations will be almost unique for every item in the scene so I cannot think of any other way than this. 

And yes I would recommend keeping them in the state, or as class variables, or static variables rather than recreating them every render. Recreating every render is still not too bad BTW, but if you have a lot of them it may be a bottleneck.

With some examples you can just modify the variables yourself instead of updating the state, see the 2nd benchmark for example, that one's quite fast but only necessary if you would like to sacrifice some benefits of react...

**Comment by agrande** [comment]
I was thinking more along the line of <object3D position={[1, 2, 3]}/>.

If only array literals could be interned like strings, we would only require a simple pointer equality check.
[1, 2, 3] == [1, 2, 3] would be true, and it would be both efficient and convenient to work with vectors.

I see 3 different ways to use vectors (as any other type of value):

1. Have a static value which never changes, in which case it would make sense to have its value declared exactly where it's used. It makes code more readable, since you don't have to jump around to check the actual value. Less code too.
2. Have a value computed from react state and props when render() is called.
3. Have a value manipulated through react state.

(3) is efficient and works as needed.
The problem is (1) and (2), which are unfortunately the most common cases, the whole point of using react being to minimize and isolate state.

I suppose javascript makes it impossible to solve this simplicity vs performance trade-off.
As you said, recreating a vector at every render is maybe not as bad as it sounds in most cases.

Thanks!

**Comment by toxicFork** [comment]
Closing issue for now, until comparing arrays is cheaper in js, or until we have different approaches :) Feel free to reopen!

For (1)... I guess something can be done as a babel plugin to have a static variable that could be evaluated only once or something? I guess you can already do this for now: a static variable in the class and do `position={MyClass.myPos}`
