### ISSUE TITLE
Check which props are used for RawShaderMaterial

### ISSUE THREAD

**Issue by toxicFork** [toxicFork/react-three-renderer#34]
Could try the existing props and see which one works, or may need to read through THREE.js source.

- [x] uniforms
  - [ ] Support both child element and attribute
- [x] wireframe
- [x] vertex and frag shaders

**Comment by DelvarWorld** [comment]
I'm currently getting this:

    Warning: Foreign prop uniforms found in rawShaderMaterial. Check the render method of `Editor`.

I assumed they would come from inheriting `ShaderMaterialDescriptor` but it looks like because [the constructor](https://github.com/toxicFork/react-three-renderer/blob/master/src/lib/descriptors/Material/ShaderMaterialDescriptor.js#L28) is overwritten in `rawShaderMaterial` they won't be there.

**Comment by DelvarWorld** [comment]
A RawShaderMaterial is just a very thin wrapper around raw glsl in Threejs. It basically just facilitates passing threejs type uniforms to raw glsl code. Any of the properties like lights, fog, morph, skinning, etc, only apply to a ShaderMaterial (or others like MeshPhongMaterial), because there's code in the shader (or code is re-compiled into the shader) to handle those arguments passed in as attributes/uniforms/etc.

A rawshader only has a vertex, fragment, and uniforms.

**Comment by toxicFork** [comment]
Hmmm... try using <uniforms> within [like this](https://github.com/toxicFork/react-three-renderer-example/blob/master/src/examples/AnimationCloth/StaticWorld.js#L115) :)

I should add more documentation for this

Let me know if that didn't work

**Comment by DelvarWorld** [comment]
Ah I see. I'm implementing the [ShaderFrog runtime](https://github.com/DelvarWorld/ShaderFrog-Runtime) so I can use shaders exported from [http://shaderfrog.com/app](http://shaderfrog.com/app). I get a regular Three uniforms object out of the process. I would need to do some kind of manipulating to fit it into the `<uniform />` structure.

I'm a bit confused though - with this change, even though I get the warning the uniforms seem to be passed correctly, and my shaders show up correctly.

**Comment by toxicFork** [comment]
Yes the warnings are just to help things but they won't block the props from being passed in :) 

Also it may not work if you choose to use another value for the "uniforms" prop because it won't know how to update. I think by default it should recreate the shader so it would work but may be unnecessarily expensive.

I can think of some edge cases where someone adds both uniforms prop and child element for example, that may cause bad things, I can add warnings if they do both, otherwise yes it should work

**Comment by toxicFork** [comment]
The parameters that will not be used for rawShaderMaterial are:
- precision
- supportsVertexTextures
- map
- envMap
- envMap
- lightMap
- aoMap
- emissiveMap
- bumpMap
- normalMap
- displacementMap
- specularMap
- roughnessMap
- metalnessMap
- alphaMap
- vertexColors
- flatShading
- skinning
- useVertexTexture
- morphTargets
- morphNormals
- doubleSided
- flipSided
- shadowMapEnabled
- pointLightShadows
- sizeAttenuation
- logarithmicDepthBuffer
- alphaTest ( currently present in both, will need to be removed )
- useFog
- fog
- fogExp

Properties still used:
- transparent
- wireframe
- wireframeLinewidth
- visible
- side
- opacity ( used for passing in uniforms.opacity it seems )
